sudo: false
dist: "trusty" # otherwise 'python3-pip' won't be available
language: python
python: 3.7
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxml2-dev
  - sudo apt-get install -y chromium-chromedriver python pip3