language: python
python:
  - "2.7"
cache: pip
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
install:
  - pip install -r requirements.txt
script:
  - python navigate1.py