sudo: false
dist: "trusty" # otherwise 'python3-pip' won't be available
language: python
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

before_install:
  - "pip3 install selenium"