from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
import time

class Navigate():
    def __init__(self):
        self.browserProfile = webdriver.ChromeOptions()
        self.browserProfile.add_argument('--headless')
        self.browserProfile.add_argument('window-size=2024,1024')
        self.driver = webdriver.Chrome(options=self.browserProfile)
        self.actions = ActionChains(self.driver)
        dimensions = self.driver.get_window_size()
        print(dimensions)

    def goToSite(self):
        self.driver.get('https://smartcinema.co/')
        print('Initialized successfully')
        time.sleep(2)

    def descend(self):
        page = self.driver.find_element_by_tag_name('body')
        page.send_keys(Keys.ARROW_DOWN)
        print('scrolled down!')
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        print('scrolled down!')
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        print('scrolled down!')
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        print('descended further down the page')
        time.sleep(2)

    def mouse_over_movies(self):
        print('Let\'s check those movies!')
        movies = self.driver.find_elements_by_class_name('product-type-simple')
        hover = ActionChains(self.driver).move_to_element(movies[10])
        hover.perform()
        time.sleep(1)
        hover = ActionChains(self.driver).move_to_element(movies[9])
        hover.perform()
        time.sleep(1)
        hover = ActionChains(self.driver).move_to_element(movies[0])
        hover.perform()
        time.sleep(1)
        movies[0].click()
        time.sleep(1)

    def add_to_cart(self):
        print('Add to cart')
        addToCartBtn = self.driver.find_element_by_name('add-to-cart')
        hover = ActionChains(self.driver).move_to_element(addToCartBtn)
        hover.perform()
        time.sleep(1)
        addToCartBtn.click()
        time.sleep(1)

    def view_cart(self):
        print('View cart')
        time.sleep(1)
        viewCartBtn = self.driver.find_element_by_class_name('wc-forward')
        hover = ActionChains(self.driver).move_to_element(viewCartBtn)
        hover.perform()
        time.sleep(1)
        viewCartBtn.click()
        time.sleep(2)

    def checkout(self):
        print('Go to checkout')
        goToCheckout = self.driver.find_element_by_class_name('checkout-button')
        hover = ActionChains(self.driver).move_to_element(goToCheckout)
        hover.perform()
        time.sleep(1)
        goToCheckout.click()
        time.sleep(2)

    def checkout_form(self):
        print('fill in the form')
        firstName = self.driver.find_element_by_id('billing_first_name')
        hover = ActionChains(self.driver).move_to_element(firstName)
        hover.perform()
        time.sleep(0.5)
        firstName.send_keys('Selenium')
        time.sleep(0.5)
        lastName = self.driver.find_element_by_id('billing_last_name')
        hover = ActionChains(self.driver).move_to_element(lastName)
        hover.perform()
        time.sleep(0.5)
        lastName.send_keys('Webdriver')
        time.sleep(0.5)
        orderComments = self.driver.find_element_by_id('order_comments')
        hover = ActionChains(self.driver).move_to_element(orderComments)
        hover.perform()
        time.sleep(0.5)
        orderComments.send_keys('Urgent delivery')
        time.sleep(0.5)
        company = self.driver.find_element_by_id('billing_company')
        hover = ActionChains(self.driver).move_to_element(company)
        hover.perform()
        time.sleep(0.5)
        company.send_keys('Selenium SRO')
        time.sleep(0.5)
        address1 = self.driver.find_element_by_id('billing_address_1')
        hover = ActionChains(self.driver).move_to_element(address1)
        hover.perform()
        time.sleep(0.5)
        address1.send_keys('Milady Horakove 13')
        time.sleep(0.5)
        page = self.driver.find_element_by_tag_name('body')
        page.send_keys(Keys.ARROW_DOWN)
        print('scrolled down!')
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        print('scrolled down!')
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        print('scrolled down!')
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        time.sleep(0.5)
        page.send_keys(Keys.ARROW_DOWN)
        city = self.driver.find_element_by_id('billing_city')
        hover = ActionChains(self.driver).move_to_element(city)
        hover.perform()
        time.sleep(0.5)
        city.send_keys('Brno')
        time.sleep(0.5)
        postCode = self.driver.find_element_by_id('billing_postcode')
        hover = ActionChains(self.driver).move_to_element(postCode)
        hover.perform()
        time.sleep(0.5)
        postCode.send_keys('602 00')
        time.sleep(0.5)
        phoneNum = self.driver.find_element_by_id('billing_phone')
        hover = ActionChains(self.driver).move_to_element(phoneNum)
        hover.perform()
        time.sleep(0.5)
        phoneNum.send_keys('606222333444')
        time.sleep(0.5)
        email = self.driver.find_element_by_id('billing_email')
        hover = ActionChains(self.driver).move_to_element(email)
        hover.perform()
        time.sleep(0.5)
        email.send_keys('selenium_webdriver@gmail.com')
        time.sleep(1)

    def finish_order(self):
        print('finishing the order')
        placeOrder = self.driver.find_element_by_id('place_order')
        hover = ActionChains(self.driver).move_to_element(placeOrder)
        hover.perform()
        placeOrder.click()
        time.sleep(5)

    def post_order(self):
        print('order is finished')
        productName = self.driver.find_element_by_class_name('woocommerce-table__product-name')
        hover = ActionChains(self.driver).move_to_element(productName)
        hover.perform()
        print('mouse over product name')
        time.sleep(1)
        priceAmount = self.driver.find_element_by_class_name('woocommerce-Price-amount')
        hover = ActionChains(self.driver).move_to_element(priceAmount)
        hover.perform()
        print('mouse over product price')
        time.sleep(1)
        merchandise = self.driver.find_element_by_id('menu-item-29')
        hover = ActionChains(self.driver).move_to_element(merchandise)
        hover.perform()
        print('mouse over merchandise')
        merchandise.click()
        time.sleep(1)
        siteLogo = self.driver.find_element_by_id('logo')
        hover = ActionChains(self.driver).move_to_element(siteLogo)
        hover.perform()
        print('mouse over logo')
        siteLogo.click()
        time.sleep(2)

    def finish(self):
        self.driver.quit()